name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"  # 每3天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 添加超时限制

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # 启用pip缓存
      
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: playwright-${{ runner.os }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
      
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests user-agent python-dotenv
      
      - name: Install Playwright and browsers
        run: |
          playwright install
          playwright install-deps
      
      - name: Run login script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
          PROXY_URLS: ${{ secrets.PROXY_URLS }}
        run: |
          python login_script.py
